<?php

$menuprodeclaration = array("menu" => array(
    "Protection" => array(
        "Coupure, protection, répartition" => array(
            "Disjoncteurs, interrupteurs ouverts" => array(
                "DMX³ 1600 - disjoncteurs ouverts de 630 à 1600 A",
                "DMX³ 2500 - disjoncteurs ouverts de 630 à 2500 A",
                "DMX³ 4000 - disjoncteurs ouverts 3200 à 4000 A",
                "DMX³ 6300 - disjoncteurs ouverts 5000 à 6300 A",
                "DMX³ 2500/4000/6300 - unités de protection électroniques",
                "DMX³-I 2500/4000/6300 - interrupteurs ouverts de 1250 à 6300 A",
                "DMX³ 2500/4000/6300 - équipements, accessoires et services"),
            "Disjoncteurs de puissance boîtiers moulés" => array(
                "DPX³ 160 magnétothermiques - disjoncteurs de puissance de 16 à 160 A",
                "DPX³ 160 magnétothermiques différentiels - disjoncteurs de puissance de 16 à 160 A",
                "DPX³ 160 magnétothermiques  - version extractible et accessoires",
                "DPX³ 250 magnétothermiques - disjoncteurs de puissance de 100 à 250 A",
                "DPX³ 250 électroniques - disjoncteurs de puissance de 40 à 250 A",
                "DPX³ 250 électroniques avec unité de mesure - disjoncteurs de puissance de 40 à 250 A",
                "DPX³ 250 - version extractible et accessoires",
                "DPX³ 160/250 - accessoires et auxiliaires communs",
                "DPX™ 250 - disjoncteurs de puissance magnétothermiques et électroniques de 40 à 250 A",
                "DPX™ 250 - disjoncteurs de puissance magnéto-thermiques et électroniques de 40 à 250 A",
                "DPX™ 250 - équipement et commandes",
                "DPX³ 630 - disjoncteurs de puissance magnétothermiques et électroniques de 250 à 630 A",
                "DPX³ 630 - équipement et commandes",
                "DPX³ 1600 - disjoncteurs de puissance magnétothermiques et électroniques de 630 à 1600 A",
                "DPX³ 1600 - équipements et commandes",
                "DPX³/DPX³-I 630 et 1600 - auxiliaires de signalisation et commande",
                "Relais différentiel et tores",
                "DPX³ - alimentation et supervision",
                "DPX³-AB - disjoncteurs de branchement version ERDF de 90 à 400 A",
                "DPX³ magnétique seul - disjoncteurs pour la protection des moteurs jusqu'à 400 A"),
            "Interrupteurs-sectionneurs" => array(
                "DPX³-I - 160 à 1600 A - interrupteurs à déclenchement libre",
                "DPX™-IS 250 - 63 à 250 A - interrupteurs-sectionneurs",
                "DPX™-IS 630 - 400 à 630 A - interrupteurs-sectionneurs",
                "DPX™-IS 1600 - 800 à 1600 A - interrupteurs-sectionneurs",
                "DPX™-IS - auxiliaires",
                "Vistop™ 32 A - interrupteurs-sectionneurs",
                "Vistop™ 63 à 160 A - interrupteurs-sectionneurs",
                "Coupure de proximité 12 à 160 A"),
            "Fusibles et disjoncteurs moteurs" => array(
                "Cartouches industrielles à couteaux - socles et accessoires",
                "Cartouches industrielles à couteaux - type gG",
                "Cartouches industrielles à couteaux - type aM et neutres à couteaux",
                "Cartouches ERDF",
                "Coupe-circuit sectionnables SP - à bornes protégées",
                "Coupe-circuit sectionneurs",
                "Cartouches industrielles cylindriques - type gG",
                "Cartouches industrielles cylindriques - type aM",
                "Disjoncteurs moteurs MPX³ - disjoncteurs moteur de 0,16 A à 100 A",
                "Disjoncteurs moteur MPX3 - accessoires",
                "Contacteurs de puissance CTX³ mini - de 6 à 16 A",
                "Relais thermiques et accessoires - pour mini-contacteurs",
                "Contacteurs de puissance CTX3 - 3 pôles - de 9 à 65 A",
                "Contacteurs de puissance CTX3 - 3 pôles - de 75 à 800 A",
                "Relais thermiques RTX3 - pour contacteurs de puissance 3-pôles CTX3",
                "Contacteurs de puissance CTX3 - 4-pôles - de 40 à 900 A",
                "Accessoires CTX3",
                "Bobines de rechange CTX3",
                "Relais de commande CTX3"),
            "Disjoncteurs de branchement et appareils de protection modulaires" => array(
                "Disjoncteurs de branchement ERDF - bipolaires et tétrapolaires",
                "Disjoncteurs différentiels de protection - bipolaires et tétrapolaires",
                "Interrupteurs-sectionneurs DX³-IS - sectionnement tête d'installation, 16 à 125 A",
                "Interrupteurs différentiels DX³-ID - protection tête de groupe - arrivée haut / départ haut",
                "Interrupteurs différentiels DX³-ID - arrivée haut / départ bas",
                "Disjoncteurs différentiels DX³ 4500 - 6 kA - courbe C - protection tête de groupe",
                "Disjoncteurs différentiels DX³ 4500 - 6 kA - courbes C et B - protection des départs",
                "Disjoncteurs DNX³ 4500 - 6 kA - courbes C et D - protection des départs",
                "Disjoncteurs DNX³ 4500 - 6 kA - courbes C - protection des départs",
                "Disjoncteurs différentiels monoblocs DX³ 6000 - 10 kA - courbe C - protection tête de groupe",
                "Disjoncteurs différentiels monoblocs DX³ 6000 - 10 kA - courbe C - protection des départs",
                "Disjoncteurs différentiels monoblocs DX³ 6000 - 10 kA - courbes C et B - protection des départs",
                "Disjoncteurs DX³ 6000 - 10 kA - courbe C - protection des départs",
                "Disjoncteurs DX³ 6000 - 10 kA - courbe B - protection des départs",
                "Disjoncteurs DX³ 6000 - 10 kA - courbe D - protection des départs monophasés",
                "Disjoncteurs DX³ 6000 - 10 kA - courbe D - protection des départs triphasés",
                "Disjoncteurs DX³ 10000 - 16 kA - courbe C - protection des départs",
                "Disjoncteurs DX³ 10000 - 16 kA - courbe B - protection des départs",
                "Disjoncteurs DX³ 10000 - 16 kA - courbe D - protection des départs",
                "Disjoncteurs DX³ - 16 kA - courant continu - protection des départs",
                "Disjoncteurs DX³ - 25 kA - courbe C - protection des départs",
                "Disjoncteurs DX³ - 25 kA - courbe B - protection des départs",
                "Disjoncteurs DX³ - 25 kA - courbe D - protection des départs",
                "Disjoncteurs DX³ MA - 25 kA magnétique seul - protection des départs",
                "Disjoncteurs DX³ - 36 kA - courbe C - protection des départs",
                "Disjoncteurs DX³ - 25 kA - courbe Z - protection des départs",
                "Disjoncteurs DX³ - 50 kA - courbe C - protection des départs",
                "Disjoncteurs DX³ - 50 kA - courbe B - protection des départs",
                "Disjoncteurs DX³ - 50 kA - courbe D - protection des départs",
                "Disjoncteurs DX³ MA - 50 kA magnétique seul - protection des départs",
                "Blocs différentiels adaptables DX³ - pour disjoncteurs 1 module/pôle - protection tête de groupe",
                "Blocs différentiels adaptables DX³ - pour disjoncteurs 1 module/pôle - protection des départs",
                "Blocs différentiels adaptables DX³ - pour DX³ et DX³-IS 1,5 module/pôle - protection des départs",
                "Auxiliaires DX³, commandes motorisées et réenclencheurs automatiques DX³",
                "Inverseurs de sources manuels et commandes déportées DX³ ",
                "Modules de raccordement par peigne et accessoires DX³ ",
                "Cartouches miniatures et coupe-circuit",
                "Cartouches domestiques et porte-fusibles à broches ",
                "Coupe-circuit pour cartouches domestiques, Pac"),
            "Répartition standard, optimisée et IS" => array(
                "Borniers de répartition",
                "Répartiteurs modulaires monoblocs et associables - 40 à 250 A",
                "Répartiteurs de rangée Lexiclic - 250 A",
                "Répartiteurs de puissance extra-plats et étagés - 125 à 400 A",
                "Raccordement - connecteurs et boîtiers de raccordement",
                "Supports isolants pour jeux de barres - coffrets et armoires XL³",
                "Supports isolants pour jeux de barres - armoires Altis",
                "Barres cuivre et accessoires",
                "Répartition horizontale HX³ jusqu'à 63 A - répartition optimisée par peignes unipolaires",
                "Répartition horizontale HX³ jusqu'à 63 A - répartition optimisée par peignes tétrapolaires",
                "Répartition horizontale HX³ jusqu'à 63 A - répartition par peignes traditionnels",
                "Répartition verticale VX³ optimisée jusqu'à 63 A - répartition par peignes",
                "Répartition verticale VX³ auto 63 et 125 A - peignes tétrapolaires à bornes automatiques",
                "Répartition horizontale HX³ auto jusqu'à 125 A - répartiteurs tétrapolaires à bornes automatiques",
                "Répartition horizontale HX³ plug 80/125 A - répartiteurs de rangée tétrapolaires",
                "Répartition horizontale HX³ optimisée jusqu'à 400 A en coffrets, armoires XL³ 400, 800, 4000 ",
                "Répartition verticale VX³ optimisée - jusqu'à 400 A en armoire XL³ 400",
                "Répartition verticale VX³ optimisée - jusqu'à 800 A en armoire XL³ 800, 4000",
                "Répartition optimisée VX³/HX³ - en armoire XL³ 4000",
                "Kits de raccordements VX³ optimisées - jusqu'à 4000 A en armoires XL³ 4000",
                "Répartition IS horizontale HX³ IS - jusqu'à 125 A en armoire XL³ 4000",
                "Répartition IS horizontale HX³ IS - jusqu'à 400 A en armoire XL³ 4000",
                "Répartition IS verticale VX³ IS jusqu'à 2000 A - en armoire XL³ 4000")),
        "Mesure, qualité de l'énergie, commande" => array(
            "Supervision et appareils de mesure" => array(
                "Système de supervision Puissance - contrôle commande et mesure à distance",
                "EMDX³ : centrales de mesure",
                "EMDX³ : compteurs d'énergie - montage sur rail",
                "Compteur d'énergie résidentiel EMDX³ : affichage et supervision",
                "Appareils de mesure sur porte",
                "Appareils de mesure sur rail",
                "Transformateurs de courant (TI) et commutateurs de mesure",
                "Batteries de condensateurs BX"),
            "Parafoudres" => array(
                "Parafoudres basse tension Type 1 (T1)",
                "Parafoudres basse tension Type 2 (T2)",
                "Parafoudres basse tension Type 2 (T2) avec protection intégrée",
                "Parafoudres pour réseaux de communication"),
            "Installations photovoltaïques" => array(
                "Coffrets photovoltaïques pré-équipés",
                "Coffrets photovoltaïques à équiper et accessoires",
                "Installations photovoltaïques - répartiteurs et bornes",
                "Protection photovoltaïque - parafoudres et fusibles dédiés",
                "Protection photovoltaïque - disjoncteurs et coffret ''coupure pompier''",
                "Protection photovoltaïque - inter-sectionneurs courant continu"),
            "Commande et programmation" => array(
                "CX³ télérupteurs",
                "CX³ auxiliaires et compensateur - pour télérupteurs standards",
                "CX³ contacteurs domestique et de puissance - avec commande manuelle",
                "CX³ contacteurs de puissance - avec commande manuelle",
                "CX³ contacteurs de puissance - sans commande manuelle",
                "Auxiliaires et module de raccordement pour contacteurs CX³",
                "Relais pour DSC gaz",
                "Alarmes techniques",
                "Interrupteurs-inverseurs, poussoirs et inters poussoirs CX³, commutateurs rotatifs",
                "Voyants à LED CX³",
                "Prises de courant et supports spéciaux",
                "Relais temporisés",
                "Minuteries électroniques",
                "Inters crépusculaires",
                "Inters horaires programmables - digitaux",
                "Inters horaires programmables - analogiques"),
            "Alimentation, chauffage et variateurs" => array(
                "Alimentations monophasées",
                "Transformateurs, sonneries et ronfleurs",
                "Télévariateurs",
                "Périphériques pour télévariateurs",
                "Variation de puissance",
                "Thermostat d'ambiance et sondes associées",
                "Délesteurs - pour installation en tout électrique",
                "Gestion du chauffage électrique - avec câblage du fil pilote")),
        "Coffrets et armoires de distribution et d'équipement" => array(
            "Programme DRIVIA™ : Coffrets - GTL systèmes saillie et encastré - Réseaux multimédia et Plexo³" => array(
                "DRIVIA 18 - coffrets 18 modules par rangée",
                "Gaine Technique Logement (GTL) DRIVIA 18 - système saillie",
                "Gaine Technique Logement (GTL) DRIVIA 18 - système encastré",
                "Réseaux multimédia DRIVIA 18 - prêts à poser",
                "Réseaux et coffrets multimédia Basiques DRIVIA 18 - prêts à poser",
                "DRIVIA 13 - coffrets 13 modules par rangée",
                "DRIVIA 13 - compléments d'installation pour coffrets",
                "Gaine Technique Logement (GTL) DRIVIA 13 - système saillie complet ou à composer",
                "Gaine Technique Logement (GTL) DRIVIA 13 - système encastré",
                "Gaine Technique Logement - bacs 1 travée isolants",
                "Réseaux multimédia DRIVIA 13 - prêts à poser",
                "Coffrets Multimédia Basiques DRIVIA 13 - avec brassage",
                "Coffrets Multimédia Basiques DRIVIA 13 - sans brassage",
                "Cache-bornes et coffret 27 modules",
                "Coffrets modulaires encastrés",
                "Coffrets Plexo³",
                "Coffrets Plexo³ - gaines multifonctions et accessoires",
                "Tableautins et coffrets - équipés pour machinerie ascenseur DTU (Document Technique Unifié édité par le CSTB (Centre Scientifique et Technique du Bâtiment"),
            "Coffrets et armoires XL³" => array(
                "XL³ 125 - coffrets de distribution 18 modules",
                "XL³ 160 - 24 modules par rangée - coffrets de distribution isolants ''prêts à l'emploi''",
                "XL³ 160 - 24 modules par rangée - coffrets de distribution encastrés ''prêts à l'emploi''",
                "XL³ 160 - 24 modules par rangée - équipements et accessoires",
                "XL³ 160 - coffrets de distribution métal ''prêts à l'emploi''",
                "XL³ 160 - portes et accessoires",
                "XL³ 160 - équipements, raccordement des conducteurs de protection",
                "XL³ 400 - coffrets et armoires de distribution",
                "XL³ 400 - portes et équipements",
                "XL³ 400 - coffrets de distribution IP 55",
                "XL³ 400 - équipements pour branchements à puissance limitée (tarif bleu) et à puissance surveillée (tarif jaune)",
                "XL³ 400, équipements pour montage modulaire - Vistop jusqu'à 160 A, DPX³ 160, DPX³ 250 et DPX-IS 250 sur rail symétrique",
                "XL³ 400, équipements - pour montage DPX³ 160, DPX³ 250 et DPX-IS 250 sur platine",
                "XL³ 400 - équipements pour montage DPX 250 et DPX³ 630 sur platine",
                "XL³ 400 - équipements pour montage des appareils en gaines à câbles",
                "XL³ 400 - accessoires et plastrons",
                "XL³ 400 - accessoires de circulation de filerie et de raccordement",
                "XL³ 800 - coffrets de distribution et gaines à câbles, portes",
                "XL³ 800 - armoires de distribution",
                "XL³ 800 - coffrets de distribution IP 55",
                "XL³ 800 - armoires de distribution IP 55",
                "XL³ 800 - fixation des câbles, socles, cloisons de compartimentage et accessoires",
                "XL³ 800 - équipements pour montage modulaire Vistop jusqu'à 160 A, DPX³ 160, DPX³ 250 et DPX-IS 250 sur rail symétrique",
                "XL³ 800 - équipements pour montage DPX-IS 250, 630, 1600 et DPX³ 630 sur platine",
                "XL³ 800 - équipements pour montage DPX³ 160 et DPX³ 250 sur platine",
                "XL³ 800 - équipements pour montage DPX³ 630 et 1600 sur platine",
                "XL³ 800 - accessoires et plastrons",
                "XL³ 4000 - armoires et gaines à câbles composables, équipements",
                "XL³ 4000 - portes et accessoires",
                "XL³ 4000 - équipement pour montage modulaire Vistop jusqu'à 160 A, DPX³ 160, 250 et DPX-IS 250 sur rail symétrique",
                "XL³ 4000 - équipements pour montage DPX³ 160 et DPX³ 250 sur platine",
                "XL³ 4000 - équipement pour montage DPX³ 630 et 1600 sur platine fixe",
                "XL³ 4000 - équipements pour montage DPX³ 160 et DPX³ 250 version fixe sur platine réglable",
                "XL³ 4000 - équipements pour montage DPX³ 160 et DPX³ 250 version extractible sur platine réglable",
                "XL³ 4000 - montage des DPX³ 630 version fixe sur platines réglables",
                "XL³ 4000 - montage des DPX 250, DPX³ 630 version extractible ou débrochable sur platines réglables",
                "XL³ 4000 - montage des DPX³ 1600 version fixe sur platines",
                "XL³ 4000 - montage des DPX³ 1600 versions débrochables et inverseurs de sources sur platines réglables",
                "XL³ 4000 - montage des DMX³ versions fixe ou débrochable",
                "XL³ 4000 - plastrons et accessoires",
                "XL³ 4000 - accessoires",
                "XL³ 6300 - armoires composables et équipements",
                "XL³ 4000 et 6300 - choix des équipements pour les formes"),
            "Canalisations de puissance" => array(
                "Canalisations électriques préfabriquées MR - canalisations de moyenne puissance 160 à 1000 A"),
            "Boitiers, coffrets et pupitres de commande" => array(
                "Boîtiers industriels Atlantic métal et inox - IP 66 - IK 10 - Nema 4",
                "Boîtiers industriels Atlantic métal et inox - équipements",
                "Boîtiers industriels plastique",
                "Boîtiers industriels plastique - accessoires",
                "Coffrets métal Atlantic",
                "Coffrets métal Atlantic associables",
                "Coffrets métal Atlantic - équipements",
                "Coffrets métal Atlantic - accessoires",
                "Atlantic axis - pupitres de commande métal",
                "Atlantic axis - accessoires pour pupitres de commande métal",
                "Coffrets Atlantic inox spécial agroalimentaire",
                "Coffrets Atlantic inox - 304 L et 316 L",
                "Coffrets Marina - polyester",
                "Coffrets Marina - équipements",
                "Armoires Marina - polyester",
                "Armoires Marina - équipements",
                "Coffrets Atlantic, Atlantic inox, Marina - plaques",
                "Atlantic, Atlantic inox, Marina - équipements communs pour coffrets",
                "Atlantic, Atlantic inox, Marina - équipements de distribution pour coffrets",
                "Atlantic, Atlantic inox, Marina - équipements et accessoires communs",
                "Coffrets - fermetures",
                "Atlantic, Atlantic inox, Marina - fixation de coffrets au sol et sur poteau"),
            "Armoires" => array(
                "Armoires Altis™ monoblocs métal",
                "Armoires Altis™ monoblocs métal - accessoires",
                "Armoires Altis™ assemblables métal",
                "Armoires de distribution Altis™",
                "Armoires Altis™ 19'' métal et équipements",
                "Armoires Altis™ métal - équipements",
                "Armoires Altis™ métal - plaques passe-câbles",
                "Armoires Altis™ assemblables métal - accessoires",
                "Armoires Altis™ monoblocs et assemblables inox",
                "Armoires Altis™ monoblocs et assemblables inox - accessoires",
                "Armoires Altis™ inox - équipements",
                "Armoires Altis™ - plaques",
                "Armoires Altis™ - équipements",
                "Armoires Altis™ - éclairage",
                "Armoires Altis™ - accessoires",
                "Armoires Altis™ - fermetures",
                "Coffrets et armoires - montants, rails et fixation de l'appareillage"),
            "Gestion thermique" => array(
                "Gestion thermique des coffrets et armoires - ventilateurs",
                "Gestion thermique des coffrets et armoires - chauffage et régulation",
                "Gestion thermique des armoires - échangeurs et climatiseurs"))),
    "Industrie" => array(
        "Alimentation, commande, signalisation, composants de câblage" => array(
            "Alimentations, transformateurs" => array(
                "Alimentations stabilisées à découpage - monophasées",
                "Alimentations stabilisées à découpage - mono / biphasées et triphasées",
                "Alimentations stabilisées à découpage - fonctions complémentaires",
                "Alimentations redressées filtrées - monophasées",
                "Alimentations redressées non filtrées - monophasées",
                "Alimentations stabilisées filtrées - secourues",
                "Transformateurs de commande et de signalisation - monophasés - connexion automatique",
                "Transformateurs de commande et de signalisation - monophasés - connexion à vis",
                "Transformateurs d'équipement - monophasés",
                "Transformateurs - CNOMO - TDCE - versions I et II",
                "Transformateurs TFCE avec protection intégrée - monophasés nus",
                "Transformateurs monophasés - IP 21",
                "Transformateurs triphasés - IP 21",
                "Transformateurs monophasés - IP 55 - Classe II",
                "Autotransformateurs - IP 55 - IP 21 - IP 00",
                "Transformateurs pour locaux hospitaliers - IP 21"),
            "Commandes" => array(
                "Osmoz complets : appareils non-lumineux - auxiliaires de commande et de signalisation",
                "Osmoz complets : appareils lumineux - auxiliaires de commande et de signalisation",
                "Osmoz boîtes à boutons équipées - auxiliaires de commande et de signalisation",
                "Osmoz composables : têtes non lumineuses - auxiliaires de commande et de signalisation",
                "Osmoz composables : têtes lumineuses - auxiliaires de commande et de signalisation",
                "Osmoz composables : sous-ensembles blocs - auxiliaires de commande et de signalisation",
                "Osmoz blocs : éléments de base - auxiliaires de commande et de signalisation",
                "Osmoz boîtes à boutons - auxiliaires de commande et de signalisation",
                "Osmoz accessoires - auxiliaires de commande et de signalisation",
                "Osmoz étiquettes - auxiliaires de commande et de signalisation",
                "Interrupteurs-sectionneurs rotatifs complets de 20 à 100 A",
                "Interrupteurs-sectionneurs rotatifs complets de 16 à 80 A",
                "Interrupteurs-sectionneurs rotatifs composables de 20 à 100 A",
                "Interrupteurs-sectionneurs rotatifs composables de 20 à 100 A - accessoires",
                "Commutateurs à cames - fixation par vis sur porte - de 16 à 63 A",
                "Commutateurs à cames - fixation centrale Ø22 sur porte - 10 A (mini-commutateurs) et 16 A",
                "Commutateurs à cames - boîtiers - de 16 à 63 A",
                "Inters horaires programmables 72 x 72",
                "Modules à diodes, de commande et électronique"),
            "Presse-étoupe et conduits flexibles" => array(
                "Presse-étoupe plastique IP 66 à entrées multiples et passe-fil",
                "Presse-étoupe plastique IP 68",
                "Presse-étoupe plastique IP 55",
                "Presse-étoupe métal IP 68",
                "Ecrous pour presse-étoupe",
                " Bouchons et adaptateurs PG/ISO plastique IP 68",
                "système conduits flexibles RTA polyamide LGP - avec raccords et dérivations polyamide",
                "système conduits flexibles RTA PVC FP 2000 et métallo-plastique - avec raccords métal",
                "système conduits flexibles RTA PVC - avec raccords plastique"),
            "Connexion" => array(
                "Blocs de jonction de puissance Viking™ 3",
                "Blocs de jonction connexion à vis Viking™ 3 - pour câble cuivre",
                "Blocs de jonction connexion à vis Viking™ 3 pour câble cuivre - pour câble cuivre",
                "Blocs de jonction connexion à ressort Viking™ 3 - pour câble cuivre",
                "Blocs de jonction Viking™ 3 - accessoires"),
            "Goulottes, embouts et repérage" => array(
                "Starfix™ - embouts de câblage",
                "Starfix™ - pinces",
                "Starfix™ - chargeurs",
                "Système de repérage CAB 3™ - pour filerie et blocs de jonction Viking 3",
                "Plaques repères - pour blocs de jonction Viking 3",
                "Système de repérage CAB 3™ - accessoires",
                "Système de repérage Mémocab™ - pour filerie",
                "Système de repérage Duplix™ - pour câbles",
                "Etiquettes de repérage - pour imprimante laser",
                "Recharges pour titreuse Logicab™ 2 et anciennes titreuses",
                "Repères pour imprimante Logicab™ 2",
                "Repères et accessoires pour table traçante Logicab™ 2",
                "Goulottes Lina 25™",
                "Colliers d'équipement Colring™",
                "Colliers d'équipement Colring™ - accessoires")),
        "Transformation et distribution de l'énergie" => array(
            "Prises et bornes pour véhicules électriques" => array(
                "Bornes Green'up™ Premium monophasées type 3 - pour recharge de véhicules électriques",
                "Bornes Green'up™ Premium triphasées type 3 - pour recharge de véhicules électriques",
                "Prêt à poser Green'up™ Access - pour recharge de véhicules électriques",
                "Borne Green'up™ Access - pour recharge de véhicules électriques",
                "Prises Green’up ™ Access - pour recharge de véhicules électriques",
                "Bornes Green’up™ Premium monophasées - pour recharge de véhicules électriques",
                "Bornes Green’up™ Premium triphasées - pour recharge de véhicules électriques",
                "Gestion de l'infrastructure de recharge pour véhicules électriques"),
            "Connecteurs multipôles et prises Hypra" => array(
                "Kits de connecteurs multipôles Hypra plastique, métal",
                "Connecteurs multipôles Hypra plastique, métal"),
            "Prises Hypra IP 44" => array(
                "Hypra IP 44 et IP 66/67-55 - BT 16 A - prises à brochage domestique",
                "Hypra IP 44 - TBT 16 et 32 A - prises, fiches et prises mobiles",
                "Hypra BT 16 A - IP 44/55 - Prisinter",
                "Hypra BT 16 A - IP 44 - prises",
                "Hypra BT 16 A - IP 44 - fiches et prises mobiles",
                "Hypra BT 32 A - IP 44/55 - Prisinter",
                "Hypra BT 32 A - IP 44 - prises",
                "Hypra BT 32 A - IP 44 - fiches et prises mobiles",
                "Hypra BT 63 A - IP 44 - Prisinter",
                "Hypra BT 63 A - IP 44 - prises",
                "Hypra BT 63 A - IP 44 - fiches et prises mobiles"),
            "Prises Hypra IP 66/67-55" => array(
                "Hypra BT 16 A - IP 66/67-55 - prises, fiches et prises mobiles",
                "Hypra BT 32 A - IP 66/67-55 - prises, fiches et prises mobiles",
                "Hypra BT 63 A - IP 66/67-55 - prises, fiches et prises mobiles",
                "Hypra BT 125 A - IP 66/67-55 - prises, fiches et prises mobiles",
                "Hypra IP 44 - remplacement Martin Lunel - prises transfert direct BT 16 et 32 A"),
            "Coffrets Hypra" => array(
                "Coffrets Hypra IP 44 monoprise équipés",
                "Coffrets Hypra IP 66/67-55 monoprise équipés",
                "Coffrets Hypra IP 44 multiprises équipés",
                "Coffrets Hypra IP 66/67-55 multiprises équipés",
                "Coffrets Hypra à composer"),
            "Prises P 17" => array(
                "P 17 - BT 16 et 32 A - IP 44 - prises et fiches inverseurs de phase",
                "P 17 - BT 16 et 32 A - IP 44 - fiches et prises mobiles",
                "P 17 - TBT 16 et 32 A - IP 44 - prises, fiches et prises mobiles",
                "P 17 - BT 16 A - IP 54 - brochage domestique",
                "P 17 - BT 16 et 32 A - IP 66/67 - prises, fiches et prises mobiles",
                "P 17 - BT 63 et 125 A - IP 66/67 - prises, fiches et prises mobiles"),
            "Coffrets de prises et de chantier P 17" => array(
                "Coffrets P 17 équipés BT 16 à 63 A",
                "Accessoires - pour réalisation de coffrets mobiles P 17",
                "Coffrets P 17 à composer",
                "Coffrets de chantier P 17 - coffrets d'étages",
                "Coffrets de chantier P 17 - coffrets corps de métier",
                "Coffrets de chantier P 17 - coffrets de distribution"),
            "Blocs de sécurité et prises ML" => array(
                "Blocs de sécurité BS 24 - BSM",
                "Martin Lunel - BT de 10 à 125 A - Prisinter",
                "Martin Lunel - BT et TBT de 10 à 125 A - fiches et prises de courant",
                "Martin Lunel - 3 A, 10 A et 16 A - prises et fiches à brochage domestique, interrupteurs, boutons - poussoirs"))),
    "Résidentiel" => array(
        "Solutions domotiques et multimédia pour la maison" => array(
            "Multimédia" => array(
                "Réseau multimédia Optimum auto Gigabit - prêt à poser et offre à composer pour version automatique",
                "Réseau multimédia Optimum manuel - prêt à poser et offre à composer pour version manuelle",
                "Réseau multimédia Triple Play Gigabit - prêt à poser et offre à composer pour version automatique Triple Play Gigabit",
                "Réseau multimédia Mixte - prêt à poser et offre à composer pour version manuelle",
                "Réseau multimédia Basique - prêt à poser, coffrets et équipements",
                "Câbles et cordons - pour réseau multimédia",
                "DTI, fiches et prises téléphone",
                "Prises multimédia et informatique - point d'accès Wi-Fi, accessoires coffrets multimédia, prises TV, doubleurs et prise optique",
                "Amplificateurs TV/SAT et connectique",
                "FttH - Fibre optique jusqu'à l'abonné - solution préconnectorisée",
                "FttH - Fibre optique jusqu'à l'abonné - solution pré-câblée - Nécessite un épissurage par fusion"),
            "MyHOME® domotique - BUS" => array(
                "MyHOME® domotique - BUS - intégration et contrôle",
                "MyHOME® domotique - BUS - automatisme - commandes",
                "MyHOME® domotique - BUS - automatisme - interfaces et télécommandes",
                "MyHOME® domotique - BUS - automatisme - détecteurs de mouvements",
                "MyHOME® domotique - BUS - automatisme - commandes Sans Fil (émetteurs)",
                "MyHOME® domotique - BUS - automatisme - actionneurs commandes",
                "MyHOME® domotique - BUS - automatisme - actionneurs",
                "MyHOME® domotique - BUS - automatisme - gestion avancée de volets motorisés",
                "MyHOME® domotique - BUS - gestion de température - centrales, thermostats et écrans tactiles",
                "MyHOME® domotique - BUS - gestion de température - sondes - thermostats",
                "MyHOME® domotique - BUS - gestion de température - actionneurs et interfaces",
                "MyHOME® domotique - BUS - mesure et affichage des consommations",
                "MyHOME® domotique - BUS - gestion d'énergie - délestage",
                "MyHOME® domotique - BUS - gestion d'énergie",
                "MyHOME® domotique - BUS - alarme intrusion - centrales",
                "MyHOME® domotique - BUS - alarme intrusion - activateurs",
                "MyHOME® domotique - BUS - alarme intrusion - détecteurs volumétriques",
                "MyHOME® domotique - BUS - alarme intrusion - détecteurs volumétriques et périmétriques",
                "MyHOME® domotique - BUS - alarme intrusion - détecteurs alarmes techniques",
                "MyHOME® domotique - BUS - alarme intrusion et alarmes techniques - dispositifs radio",
                "MyHOME® domotique - BUS - alarme intrusion - sirènes et batteries",
                "MyHOME® domotique - BUS - diffusion sonore - mixers audio/vidéo, amplificateurs, sources",
                "MyHOME® domotique - BUS - diffusion sonore - commandes",
                "MyHOME® domotique - BUS - diffusion sonore - hauts-parleurs, accessoires",
                "MyHOME® domotique - BUS - Art d'Arnould collection Epure",
                "MyHOME® domotique - BUS - portiers vidéo Céliane™",
                "MyHOME® domotique - BUS - produits hôtels",
                "MyHOME® domotique - BUS - dispositifs communs - alimentations et câbles",
                "MyHOME® domotique - BUS - dispositifs communs - configuration",
                "MyHOME® domotique - BUS - enjoliveurs Céliane™",
                "MyHOME® domotique - BUS - manettes Axolute",
                "MyHOME® domotique - BUS - manettes Livinglight",
                "MyHOME® domotique - BUS - manettes Espace Evolution"),
            "MyHOME® Play" => array(
                "MyHOME® Play - prêts à poser",
                "MyHOME® Play - commandes Sans Fil(émetteurs) pour lumières",
                "MyHOME® Play - commandes Sans Fil(émetteurs) volets et scénarios et détecteurs de mouvements",
                "MyHOME® Play - commandes Sans Fil(émetteurs) tactiles, télécommandes et interfaces",
                "MyHOME® Play - interrupteurs récepteurs pour lumières",
                "MyHOME® Play - variateurs récepteurs pour lumières, interrupteurs récepteurs pour volets",
                "MyHOME® Play - émetteurs pour alarmes techniques",
                "MyHOME® Play - enjoliveurs Céliane™",
                "MyHOME® Play - manettes Axolute",
                "MyHOME® Play - manettes Livinglight"),
            "Technologie CPL" => array(
                "Programme Céliane™ CPL - enjoliveurs",
                "Programme Céliane™ CPL - courant porteur(CPL) et infrarouge(IR) - interrupteurs, interauto, interrupteurs variateurs",
                "Programme Céliane™ CPL - courant porteur(CPL) et infrarouge(IR) - télévariateurs, prisinters, interrupteur multifonctions",
                "Programme Céliane™ CPL - courant porteur(CPL) et infrarouge(IR) - commandes de volets électriques et stores",
                "Programme Céliane™ CPL - courant porteur(CPL) - gestion du chauffage",
                "Programme Céliane™ CPL - courant porteur(CPL), infrarouge(IR) - commandes de scénarios pour pilotage en local ou à distance",
                "Programme Céliane™ CPL - courant porteur en ligne(CPL) - interfaces et accessoires d'installation",
                "Programme Céliane™ CPL - détecteurs techniques")),
        "Commande et branchement pour la maison" => array(
            "Art d'Arnould | Collection" => array(
                "Univers mémoire Acier /or brossé",
                "Univers mémoire Cristal",
                "Univers Epure",
                "Boîtes d'encastrement",
                "Vis de fixation"),
            "Programme Céliane™" => array(
                "Programme Céliane™ - enjoliveurs",
                "Programme Céliane™ - plaques",
                "Programme Céliane™ - prêts à poser Sans Fil et va-et-vient Intuition",
                "Programme Céliane™ - interrupteurs et poussoirs",
                "Programme Céliane™ - écodétecteurs automatiques",
                "Programme Céliane™ - écovariateurs",
                "Programme Céliane™ - éclairage, balisage, sécurité signalisation",
                "Programme Céliane™ - commandes de volets roulants et fenêtre de toit",
                "Programme Céliane™ - commandes VMC et mécanismes à clé",
                "Programme Céliane™ - commandes de chauffage",
                "Programme Céliane™ - diffusion sonore",
                "Programme Céliane™ - carillons et prises d'aspiration centralisée",
                "Programme Céliane™ -prises de courant, sorties de câble et obturateurs",
                "Programme Céliane™ -chargeurs USB",
                "Programme Céliane™ -prises télévision, téléphone, informatiques",
                "Programme Céliane™ -prises audio / vidéo",
                "Programme Céliane™ -prises audio / vidéo, cordons et câbles",
                "Programme Céliane™ -kits de liaison Céliane, switch, points d'accès Wi-Fi",
                "Programme Céliane™ - équipements pour hôtels",
                "Programme Céliane™ - voyants, accessoires",
                "Supports universels Batibox™ - pour Programme Céliane, Mosaic et Soliroc",
                "Réhausses, obturateurs Batibox™ et cadres saillie - pour Programme Céliane et Mosaic",
                "Carillons et boutons poussoirs",
                "Détecteurs de passage, sonneries et transformateurs",
                "Dispositifs d'alarme de fumée(DAF) et détecteur d'alarme de monoxyde de carbone (CO)"),
            "Espace Evolution et Espace d'Arnould" => array(
                "Espace Evolution - commandes d'éclairage",
                "Espace Evolution - ecodétecteurs",
                "Espace Evolution - variateurs, commandes de volets roulants et de VMC",
                "Espace Evolution - prises de courant et prises télévision",
                "Espace Evolution - prises téléphone, informatique et audio-vidéo",
                "Espace Evolution - équipements pour hôtel et accessoires",
                "Espace Evolution - plaques",
                "Espace - mécanismes",
                "Espace - plaques"),
            "Livinglight et Livinglight Air de Bticino" => array(
                "Livinglight - commandes d'éclairage",
                "Livinglight - autres commandes et relais",
                "Livinglight - détecteurs",
                "Livinglight - variateurs",
                "Livinglight - éclairage, balisage, signalisation et sécurité",
                "Livinglight - commandes de volets et ventilation",
                "Livinglight - prises courant fort",
                "Livinglight - prises télévision, téléphone",
                "Livinglight - prises informatiques et connecteur fibre optique",
                "Livinglight - connecteurs audio - vidéo",
                "Livinglight - signalisation sonore et lumineuse",
                "Livinglight - produits pour hôtel et prise rasoir",
                "Livinglight - détecteurs de gaz et gestion de la température",
                "Livinglight - obturateurs, sorties de câbles, manettes et accessoires",
                "Livinglight - Idrobox IP 55",
                "Livinglight - installation sur profilés ou avec cadres saillie",
                "Livinglight - plaques carrées",
                "Livinglight - plaques rondes",
                "Livinglight - supports",
                "Livinglight - boîtes d'encastrement",
                "Livinglight Air - plaques",
                "Livinglight Air - supports",
                "Livinglight Air - boîtes d'encastrement"),
            "Axolute et Axolute Etéris de Bticino" => array(
                "Axolute - commandes d'éclairage",
                "Axolute - détecteurs",
                "Axolute - variateurs",
                "Axolute - éclairage, balisage, signalisation et sécurité",
                "Axolute - commandes de volets et ventilation",
                "Axolute - prises courant fort",
                "Axolute - prises télévision, téléphone, informatiques et connecteurs audio/vidéo",
                "Axolute - produits pour hôtel et prise rasoir",
                "Axolute - accessoires et supports lumineux",
                "Axolute - plaques elliptiques",
                "Axolute - plaques rectangulaires",
                "Axolute - supports",
                "Axolute - boîtes d'encastrement",
                "Axolute Etèris - écrans",
                "Axolute Etèris - plaques",
                "Axolute Etèris - Supports",
                "Axolute Etèris - Boîtes d'encastrement",
                "Axolute Etèris - Couvercles"),
            "Niloé™" => array(
                "Niloé™ One - le tout en un pour les professionnels",
                "Niloé™ - prêt à poser Sans Fil et va-et-vient Intuition",
                "Niloé™ - interrupteurs, va-et-vient et transformeurs",
                "Niloé™ - poussoirs",
                "Niloé™ - écodétecteurs",
                "Niloé™ - écovariateurs",
                "Niloé™ - commandes de volets, VMC et chauffage",
                "Niloé™ - prises de courant, sorties de câble et obturateur",
                "Niloé™ - intégrateur fonctions Mosaic, prises téléphone, haut-parleur, RJ 45",
                "Niloé™ - prises télévision",
                "Niloé™ - cadres saillie, accessoires",
                "Niloé™ - plaques"),
            "Programme Batibox™" => array(
                "Programme Ecobatibox - boîtes d'encastrement pour cloisons sèches",
                "Programme Batibox™ -boîtes d'encastrement pour cloisons sèches",
                "Programme Batibox™ - boîtes d'encastrement spécifiques pour cloisons sèches",
                "Programme Batibox™ -boîtes d'encastrement DCL pour cloisons sèches",
                "Programme Batibox™ - outillages, boîtes pour dérivation, pour combles et hourdis",
                "Programme Batibox™ - boitiers multimédia pour installation audio/vidéo",
                "Programme Batibox™ - boîtes d'encastrement multimatériaux",
                "Programme Batibox™ -boîtes d'encastrement pour maçonnerie",
                "Programme Batibox™ - boîtes d'encastrement pour béton",
                "Programme Batibox™ -boîtes d'encastrement DCL et dérivation pour béton"),
            "Appareillage saillie" => array(
                "Appareillage saillie - mécanismes composables",
                "Appareillage saillie version étroite - complet",
                "Appareillage saillie - complet",
                "Thermostat d'ambiance saillie et télérupteurs"),
            "Moulures et plinthes pour l'habitat" => array(
                "Prises pour plinthes, sorties de câbles et socles format réduit",
                "Guide-câbles",
                "Moulures DLPlus 20 x 12,5 - profilés, accessoires de cheminement et montage d'appareillage",
                "Moulures DLPlus 32 x 12,5 et 40 x 12,5 - profilés, accessoires de cheminement et montage d'appareillage",
                "Moulures DLPlus 32 x 16 et 40 x 16 - profilés, accessoires de cheminement et montage d'appareillage",
                "Moulures DLPlus 32 x 20 et 40 x 20 - profilés, accessoires de cheminement et montage d'appareillage",
                "Moulures DLPlus 60 x 20 et 75 x 20 - profilés, accessoires de cheminement et montage d'appareillage",
                "Accessoires d'installation des profilés",
                "Plinthes DLPlus 80 x 20 et 120 x 20 - profilés, accessoires de cheminement et montage d'appareillage",
                "Plinthe DLP 140 x 35 - profilé, accessoires de cheminement et montage d'appareillage"),
            "Portiers, verrouillage et contrôle d’accès " => array(
                "Kits résidentiels vidéo standards - kits mains libres couleur",
                "Kits résidentiels audio - kits mains libres BUS 2 fils",
                "Kits résidentiels audio - kits à combiné BUS 2 fils",
                "Kits résidentiels - accessoires confort et sécurité",
                "Platines de rue - Axolute Outdoor",
                "Platines de rue Sfera - modules électroniques",
                "Platines de rue Sfera New",
                "Platines de rue Sfera Robur",
                "Platines de rue - Linea 300",
                "Platines de rue à défilement de noms - Linea 300",
                "Platines de rue - Série 100 audio",
                "Platines de rue - Série 200 audio",
                "Platines de rue - Série 300 audio",
                "Platines de rue - Séries 100-200-300 audio - accessoires",
                "Platines de rue - Linea 2000 métal audio et vidéo",
                "Platines de rue - caméras déportées BUS 2 fils",
                "Postes intérieurs - écran tactile Axolute",
                "Postes intérieurs - Axolute Whice & Nighter",
                "Postes intérieurs - Axolute Vidéo Display",
                "Postes intérieurs - Livinglight",
                "Postes intérieurs - Axolute Etèris",
                "Postes intérieurs - Classe 300",
                "Postes intérieurs - Polyx - mains libres",
                "Postes intérieurs - Classe 100 vidéo",
                "Postes intérieurs - Classe 100 - V12E et x12B - Poste vidéo évolué",
                "Postes intérieurs - Classe 100 audio",
                "Postes intérieurs - Swing",
                "Postes intérieurs - standard de conciergerie",
                "Postes intérieurs - Sprint",
                "Postes intérieurs - Sprint L2",
                "Accessoires complémentaires d'installation BUS 2 fils - alimentations et relais",
                "Composants complémentaires d'installation BUS 2 fils - interfaces - sonneries - câbles - cavaliers de configuration",
                "Portier IP/BUS 2 fils - interface d'installation",
                "Verrouillage - gâches",
                "Verrouillage - ventouses",
                "Verrouillage - serrures et verrous motorisés",
                "Verrouillage et alimentation - alimentations",
                "Boutons - poussoirs - appareillage Livinglight",
                "Boutons - poussoirs - antivandales",
                "Portier téléphonique - Iryde",
                "Portier téléphonique - TELP I12 - Pour platines à BP",
                "Portier téléphonique - Telpass - A défilement de noms",
                "Contrôle d'accès Vigik® - centrale 1 porte et éléments actifs de système",
                "Contrôle d'accès Vigik® - badges de proximité, télécommande radio et accessoires d'installation",
                "Contrôle d'accès Vigik® - gestion du contrôle d’accès",
                "Claviers codés - Tercode 3100",
                "Claviers codés - Tercode 2050 N",
                "Claviers codés - Tercode 1060 - 2008",
                "Claviers codés et lecteurs - Sfera")),
        "Solutions Plexo™ et Soliroc™, composants, équipements et conduits" => array(
            "Programme Plexo™" => array(
                "Programme Plexo™ complet saillie IP 55",
                "Programme Plexo™ complet encastré IP 55",
                "Programme Plexo™ composable IP 55 - mécanismes de commande d'éclairage",
                "Programme Plexo™ composable IP 55 - coupure d'urgence, balisage, volets roulants, thermostat",
                "Programme Plexo™ composable IP 55 - prises de courant, prises différentielles",
                "Programme Plexo™ composable IP 55 - prises VDI et adaptateurs",
                "Programme Plexo™ composable IP 55 - détecteurs techniques",
                "Programme Plexo™ composable IP 55 - accessoires",
                "Programme Plexo™ composable IP 55 - boîtiers et supports plaques",
                "Plexo™ 66 complet IP 66 - IK 08 - commandes et prises",
                "Plexo™ 66 composable IP 66 - IK 08 - commandes, prises, boîtiers et accessoires"),
            "Programme Soliroc™" => array(
                "Programme Soliroc™ -commandes d'éclairage",
                "Programme Soliroc™ - autres commandes",
                "Programme Soliroc™ - prises, sorties de câbles"),
            "Boîtes Plexo™" => array(
                "Boîtes de dérivation Plexo™ - avec embouts à gradins, IP 55 - IK 07 - 650 °C",
                "Boîtes de dérivation Plexo™ - avec embouts à entrée directe, IP 55 - IK 07 - 650 °C",
                "Boîtes de dérivation Plexo™ - avec embouts à entrée directe, IP 55 - IK 07 - 750 °C",
                "Boîtes de dérivation Plexo™ - spécial circuit de sécurité ERP et locaux recevant des travailleurs",
                "Boîtes de dérivation Plexo™ - pour presse-étoupe ISO, IP 55 - IK 07 - 650 °C",
                "Boîtes de dérivation Plexo™ - pour presse-étoupe ISO, spécial dispositif actionné de sécurité incendie",
                "Boîtes de dérivation Plexo™ - embouts et accessoires"),
            "Connexion mobile" => array(
                "Rallonges multiprises multimédia - avec cordon",
                "Rallonges multiprises - avec cordon",
                "Blocs multiprises d'installation fixables - à câbler",
                "Blocs multiprises mobiles - à câbler",
                "Fiches multiprises et adaptateurs",
                "Fiches spéciales",
                "Rallonges et enrouleurs à usage domestique",
                "Rallonges caoutchouc pour chantier",
                "Fiches et prolongateurs - caoutchouc",
                "Fiches et blocs multiprises - caoutchouc",
                "Fiches et prolongateurs - plastiques",
                "Fiches et prolongateurs 20 et 32 A",
                "Fiches et socles 20 et 32 A"),
            "Eclairage" => array(
                "Interrupteurs et variateurs pour lampes",
                "Adaptateurs et cordons adaptateurs",
                "Douilles à usage professionnel",
                "Douilles à usage domestique",
                "Outillage",
                "Appliques - à usage domestique ou tertiaire",
                "Hublots étanches - à usage domestique ou tertiaire",
                "Hublots étanches - pour lieux publics ou environnements sévères",
                "Baladeuses à usage professionnel",
                "Baladeuses à usage domestique",
                "Enrouleurs de chantier",
                "Coffrets de protection IP 44 - pour illuminations et éclairage public"),
            "Fixation, connexion" => array(
                "Colliers d'équipement Colring™",
                "Colliers d'équipement Colring™ -accessoires",
                "Colliers - à témoin de serrage et auto - agrippants",
                "Colliers d'installation Colson™",
                "Colliers et accessoires pour fixation de tubes",
                "Fixation de câbles",
                "Bornes de connexion sans vis Nylbloc™ auto",
                "Barrettes de connexion à vis Nylbloc™, Hypo™, Suprem 960™",
                "Barrettes de connexion à vis Suprem™, bornes et blocs de jonction",
                "Raccordement de terre et de liaison équipotentielle",
                "Plots et grilles de dérivation"),
            "Conduits d'Arnould" => array(
                "Conduits TPC - Conduits enterrés pour la protection mécanique des réseaux souterrains",
                "Conduits TPC - accessoires",
                "Conduits ICTA 3522 Rai’Gliss® - conduits cintrables pour bâtiments d'habitation et bâtiments tertiaires",
                "Conduits ICTA 3422 TurboGliss® - conduits cintrables pour bâtiments d'habitation et bâtiments tertiaires",
                "Conduits ICTA 3422 Chronofil® - conduits cintrables pour bâtiments d'habitation et bâtiments tertiaires",
                "Conduits DuoGliss® 4433 - conduit cintrable annelé à haute résistance mécanique renforcé grâce à sa “double peau”",
                "Conduits ICTA 3422 OctoGliss® - la réponse sur mesure aux besoins des pieuvristes",
                "Conduits ICA 3321 OctoGliss® - la réponse sur mesure aux besoins des pieuvristes",
                "Conduits ICA 3321 TurboGliss® - dédiés aux cloisons verticales et aux faux-plafonds",
                "Conduits TINB et TIIB 3422 - spécifiques qui répondent aux exigences ERDF pour les remontées aérosouterraines",
                "Accessoires pour conduits cintrables",
                "Bouchons RT - gagnez en étanchéité et améliorez l’isolation de vos logements",
                "Goulotte GP - la gaine de protection des remontées aéro-souterraines",
                "Conduits IRL 3321 - conduits rigides pour installation en saillie en intérieur et en extérieur",
                "Conduits IRL 4554 Extral® - conduits rigides pour installation en saillie en intérieur et en extérieur",
                "Conduits IRL 4552 ZH - conduits rigides pour installation en saillie en intérieur et en extérieur",
                "Conduits MRL 5557 - conduits rigides pour installation en saillie en intérieur et en extérieur",
                "Accessoires pour conduits rigides IRL 3321",
                "Accessoires pour conduits rigides IRL 4554 EXTRAL",
                "Accessoires pour conduits rigides IRL 4552 ZH",
                "Accessoires pour conduits rigides MRL 5557")),
        "Eclairage des parties communes : hublots, appliques, luminaires et bornes" => array(
            "Hublots d’intérieur Sarlam" => array(
                "Hublots tête de lit mini Chartres",
                "Accessoires pour hublots mini Chartres",
                "Hublots intérieurs Oléron résidentiels",
                "Hublots intérieurs Oléron extra-plats et extra-plats déco",
                "Hublots intérieurs Oléron résidentiels déco",
                "Accessoires pour hublots Oléron, Oléron déco, extra-plats et extra-plats déco"),
            "Hublots étanches Sarlam et Legrand" => array(
                "Hublots résidentiels Chartres",
                "Hublots résidentiels Chartres Alu",
                "Hublots résidentiels Chartres/Chartres Alu à visière et à grille",
                "Hublots résidentiels Chartres/Chartres Alu ovales et ovales visière",
                "Accessoires pour hublots Chartres et Chartres Alu",
                "Hublots architecturaux Koréo Arc",
                "Hublots architecturaux Koréo Arc visière",
                "Hublots architecturaux Koréo Arc 2 branches",
                "Hublots architecturaux Koréo Cub",
                "Hublots architecturaux Koréo Cub grille",
                "Accessoires pour hublots Koréo Arc et Koréo Cub",
                "Hublots haute puissance HP",
                "Hublots résidentiels Pyramide",
                "Accessoires pour hublots haute puissance HP et Pyramide",
                "Hublots fonctionnels Super 400",
                "Hublots fonctionnels Métalverre",
                "Hublots fonctionnels MAP 400 et Prestichoc",
                "Hublots Legrand - à usage domestique ou tertiaire",
                "Hublots Legrand - pour lieux publics ou environnements sévères"),
            "Appliques Sarlam et Legrand" => array(
                "Appliques Prismaline - pour salles de bains et logements",
                "Appliques Fluolux² - pour sanitaires, ERP et établissements de santé",
                "Appliques Fluolux - pour sanitaires, ERP et établissements de santé",
                "Appliques Xali - pour sanitaires et ERP",
                "Appliques Prelium Bandeau - pour sanitaires, ERP et établissements de santé",
                "Appliques Bornéo LED - usage extérieur",
                "Appliques Legrand - à usage domestique ou tertiaire"),
            "Luminaires Design Sarlam" => array(
                "Luminaires d’intérieur Design Convergence A, B, C et D",
                "Luminaires d’intérieur Design Convergence E",
                "Luminaires d’intérieur Design Convergence F et FS",
                "Luminaires d’intérieur Design Convergence G",
                "Luminaires d’intérieur Design Convergence H, I et IP",
                "Luminaires d’intérieur Design Convergence ISD et ISI",
                "Luminaires d’intérieur Design Convergence J et K"),
            "Luminaires encastrés Sarlam" => array(
                "Luminaires encastrés Kalank ronds",
                "Luminaires encastrés Kalank rectangulaires sans grille",
                "Luminaires encastrés Kalank rectangulaires avec grille",
                "Luminaires encastrés Kalank ronds et rectangulaires - accessoires",
                "Luminaires encastrés cloisons sèches Kalank CS LED",
                "Luminaires encastrés faux-plafonds Downlights Kalank FP",
                "Luminaires encastrés Kalank Mini LED",
                "Luminaires encastrés de sol Kalankosol"),
            "Bornes et wallwashers Sarlam" => array(
                "Bornes Bornéo LED - usage extérieur",
                "Bornes Bornéo Slim - usage extérieur",
                "Bornes Bornéo Prim - usage extérieur",
                "Bornes Chartres - usage extérieur",
                "Wallwashers Bornéo Vertik",
                "Wallwashers Bornéo Horizon"))),
    "Tertiaire" => array(
        "Solutions pour bureaux et lieux de travail" => array(
            "Programme Mosaic fonctions" => array(
                "Programme Mosaic™ -interrupteurs et poussoirs",
                "Programme Mosaic™ -interrupteurs spéciaux et commandes tactiles",
                "Programme Mosaic™ -détecteurs et écodétecteurs",
                "Programme Mosaic™ -écovariateur universel 2 fils",
                "Programme Mosaic™ -variateurs",
                "Programme Mosaic™ -variateurs colorimétriques DALI",
                "Programme Mosaic™ -commandes de volets roulants",
                "Programme Mosaic™ -mécanismes à clé",
                "Programme Mosaic™ -poussoirs coup de poing d'urgence",
                "Programme Mosaic™ -chauffage, régulation de température",
                "Programme Mosaic™ -fonctions de signalétique lumineuse, hublots, ronfleurs et sonnerie",
                "Programme Mosaic™ -prises de courant multi supports",
                "Programme Mosaic™ -prises de courant spéciales",
                "Programme Mosaic™ -prises de courant standards internationnaux",
                "Programme Mosaic™ -sécurité et protection",
                "Programme Mosaic™ -dérivateur, sorties de câbles, obturateurs",
                "Programme Mosaic™ -prises RJ 45 LCS²",
                "Programme Mosaic™ -prises de courant type USB - micro USB",
                "Programme Mosaic™ -prises traversées",
                "Programme Mosaic™ -points d'accès Wi - Fi et switches",
                "Programme Mosaic™ -prises téléphone",
                "Programme Mosaic™ -prises télévision",
                "Programme Mosaic™ -prises informatiques",
                "Programme Mosaic™ -commandes audio / vidéo",
                "Programme Mosaic™ -prises audio et vidéo",
                "Programme Mosaic™ -autres prises audio / vidéo et sonorisation de puissance",
                "Programme Mosaic™ -plaques",
                "Batibox™ -supports universels",
                "Programme Mosaic™ -cadres saillie",
                "Programme Mosaic™ -kits postes de travail encastrés ou saillie"),
            "Distribution des courants" => array(
                "Goulottes blanc antimicrobien Programme Mosaic™ à clippage direct 50 x 80 et 50 x 130",
                "Goulotte blanc antimicrobien Programme Mosaic™ à clippage direct 50 x 180",
                "Goulotte blanc antimicrobien Programme Mosaic™",
                "Goulottes Programme Mosaic™ à clippage direct 50 x 80 et 50 x 105",
                "Goulottes Programme Mosaic™ à clippage direct 50 x 130 et 50 x 145",
                "Goulottes Programme Mosaic™ à clippage direct 50 x 180",
                "Goulottes Programme Mosaic™ à clippage direct dérivations et réhausse",
                "Prises pour goulottes Programme Mosaic™ à clippage direct",
                "Goulottes DLP monobloc 35 x 80 et 50 x 80 - couvercle 65 mm pour montage d'appareillage avec support",
                "Goulottes DLP monobloc 50 x 105 et 50 x 150 - couvercle 65 mm pour montage d'appareillage avec support",
                "Goulottes DLP monobloc 50 x 220 - couvercle 65 mm pour montage d'appareillage avec support",
                "Goulottes DLP monobloc 35 x 105 et 50 x 105 - couvercle 85 mm pour montage d'appareillage avec support",
                "Goulotte DLP monobloc 50 x 195 - couvercle 85 mm",
                "Supports pour couvercle 65 et 85 mm",
                "Goulottes DLP monobloc 50 x 150 et 65 x 150 - couvercle 130 mm pour distribution de câbles",
                "Goulottes DLP monobloc 50 x 195 et 65 x 195 - couvercle 180 mm pour distribution de câbles",
                "Goulottes DLP monobloc - accessoires complémentaires",
                "Accessoires toutes goulottes",
                "Colonnes à équiper",
                "Blocs - colonne - pour colonnes, demi - colonnes et colonnettes",
                "Modules d'éclairage pour colonnes"),
            "Mise à disposition des courants" => array(
                "Passage de plancher et plots de sol",
                "Boîtes de sol, de passage de câbles et trappes de visites",
                "Boîtes de sol à hauteur réglable 75 - 105 mm - pour plancher technique ou chape béton",
                "Boîtes de sol à hauteur réduite 65 mm - pour plancher technique ou chape béton",
                "Boîtes d'encastrement - pour boîtes de sol et trappes de visite",
                "Boîtes de sol pour charges lourdes - pour chape béton",
                "Blocs nourrices équipés - à câbler",
                "Blocs nourrices équipés - à connecter - raccordement rapide",
                "Blocs nourrices équipés - munis de cordons avec connecteurs Easybar",
                "Blocs nourrices équipés - munis de cordon(s) à raccordement rapide",
                "Blocs nourrices encastrés",
                "Programme Mosaic™ -modules de bureau encastrés",
                "Programme Mosaic™ -pop ups pour bureaux et salles de réunion",
                "Blocs équipés pour salles de réunion - munis de cordons de branchement",
                "Blocs bureaux équipés - à câbler",
                "Blocs bureaux équipés - munis de cordon de branchement",
                "Blocs bureaux à équiper"),
            "Programme Mosaic applications" => array(
                "Programme Mosaic™ écodétecteurs autonomes pour 1 circuit - détecteurs de mouvement ECO 1 pour lieux de passage sans luminosité naturelle",
                "Programme Mosaic™ écodétecteurs autonomes pour 1 circuit - détecteurs de mouvement ECO 2 pour lieux de passage avec luminosité naturelle",
                "Programme Mosaic™ écodétecteurs autonomes pour 1 circuit - détecteurs de présence ECO 2 pour lieux de travail avec luminosité naturelle",
                "Programme Mosaic™ gestion DALI - pour 1 ou 2 circuits",
                "Configurateurs de réglage et accessoires",
                "Programme Mosaic™ gestion de plusieurs circuits - contrôleurs faux plafond multicircuits pour espaces avec luminosité naturelle",
                "Programme Mosaic™ gestion de plusieurs circuits - détecteurs ECO 2 pour contrôleurs, pour lieux de passage et de travail avec luminosité naturelle",
                "Programme Mosaic™ gestion d'éclairage - commandes individuelles et centralisées BUS / SCS",
                "Programme Mosaic™ gestion d'éclairage - contrôleurs modulaires BUS / SCS",
                "Programme Mosaic™ gestion d'éclairage - écran tactile BUS / SCS",
                "Programme Mosaic™ gestion d'éclairage - passerelles, extension d'installation et accessoires BUS / SCS",
                "Programme Mosaic™ gestion d'éclairage - commandes, détecteurs et contrôleurs filaires radio",
                "Programme Mosaic™ -solutions pour pilotage du bâtiment - commandes filaires BUS / KNX",
                "Programme Mosaic™ -solutions pour pilotage du bâtiment - commandes Sans Fil et thermostat BUS / KNX",
                "Programme Mosaic™ -solutions pour pilotage du bâtiment - détecteurs BUS / KNX",
                "Programme Mosaic™ -solutions pour pilotage du bâtiment - contrôleurs faux - plafond et modulaires BUS / KNX",
                "Programme Mosaic™ -solution BUS / KNX pour exploitation de l'installation",
                "Programme Mosaic™ luminaires à LEDs - ECO 1 ECO 2 pour établissements non médicalisés et médicalisés",
                "Programme Mosaic™ appliques tête de lit - ECO 1 pour établissements non médicalisés",
                "Programme Mosaic™ appliques tête de lit - ECO 2 pour établissements non médicalisés",
                "Programme Mosaic™ appliques tête de lit à LEDs - pour établissements médicalisés, cliniques, hôpitaux, EHPAD",
                "Programme Mosaic™ appliques tête de lit à LEDs et conduit - pour établissements médicalisés, cliniques, hôpitaux, EHPAD",
                "Programme Mosaic™ commandes - pour appliques tête de lit",
                "Eclairage d'assistance à l'autonomie Programme Mosaic™",
                "Actimétrie environnementale",
                "Programme Mosaic™ actimétrie corporelle",
                "Programme Mosaic™ appel infirmière - manipulateurs et blocs d'appel",
                "Programme Mosaic™ appel infirmière - blocs de porte et phonie",
                "Programme Mosaic™ appel infirmière - voyants pour couloir",
                "Programme Mosaic™ appel infirmière - pupitre SCS pour salle infimière",
                "Programme Mosaic™ appel infirmière - pupitre IP / SCS pour salle infirmière",
                "Programme Mosaic™ appel infirmière - produits systèmes",
                "Programme Mosaic™ appel infirmière - dispositif d'errance sécurisée",
                "Programme Mosaic™ appel infirmière - pour hopitaux de jour, centres de dialyse",
                "Programme Mosaic™ blocs d'appel infirmerie",
                "Programme Mosaic™ contrôle d'accès - lecteurs extérieurs autonomes",
                "Programme Mosaic™ contrôle d'accès - lecteurs intérieurs autonomes",
                "Programme Mosaic™ contrôle d'accès - interrupteurs à badge",
                "Programme Mosaic™ contrôle d'accès - lecteurs extérieurs centralisés",
                "Programme Mosaic™ contrôle d'accès - lecteurs intérieurs centralisés et équipements",
                "Programme Mosaic™ contrôle d'accès - accessoires communs",
                "Programme Mosaic™ contrôle d'accès - ventouses et alimentations"),
            "Platinium d'Arnould" => array(
                "Prises de sol",
                "Platines à équiper",
                "Accessoires")),
        "LCS², onduleurs, systèmes pour réseaux d’information et audio / vidéo" => array(
            "Onduleurs" => array(
                "Keor multiplug - onduleurs - 600 et 800 VA",
                "Niky - onduleurs(tour) - 600 à 1500 VA",
                "Niky S - onduleurs(tour) - 1000 à 3000 VA",
                "Keor Line RT - onduleurs(rack / tour) - 1000 à 3000 VA",
                "Keor LP - onduleurs(tour) - 1000 à 3000 VA",
                "Keor S - onduleurs(tour) - 6000 à 10000 VA",
                "Daker DK - onduleurs(rack / tour) - 1000 à 10000 VA",
                "Megaline tour - onduleurs modulaires - 1250 à 10000 VA",
                "Megaline rack - onduleurs modulaires - 1250 à 5000 VA",
                "Accessoires de communication - pour tous les onduleurs et onduleurs modulaires"),
            "LCS² câblage structuré cuivre" => array(
                "Legrand cabling system™ LCS² cat . 6A - panneaux de brassage, blocs de connecteurs",
                "Legrand cabling system™ LCS² cat . 6A - câbles et cordons",
                "Legrand cabling system™ LCS² cat . 6A - prises RJ 45",
                "Legrand cabling system™ LCS² cat . 6 - panneaux de brassage, blocs de connecteurs",
                "Legrand cabling system™ LCS² cat . 6 - câbles et cordons",
                "Prises RJ 45 LCS²",
                "Legrand cabling system™ LCS² cat . 5e - panneaux de brassage, blocs de connecteurs",
                "Legrand cabling system™ LCS² cat . 5e - câbles et cordons",
                "Legrand cabling system™ LCS² cat . 5e - prises RJ 45",
                "Legrand cabling system™ LCS² - compléments aux systèmes LCS² cat . 6a, LCS² cat . 6, LCS² cat . 5e",
                "Legrand cabling system™ LCS² - prises doubleurs et accessoires",
                "Legrand cabling system™ LCS² - boîtes de distribution de zone",
                "Legrand cabling system™ LCS² - cordons dédiés pour boîtes de distribution de zone",
                "Programme Mosaic™ -mécanismes prises traversée fibre optique multimodes"),
            "LCS² câblage structuré fibre optique et Wi - Fi" => array(
                "LCS² fibre optique - FTTO(Fiber To The Office) -Full IP",
                "LCS² fibre optique - FTTD(Fiber To The Desk) -Full IP",
                "LCS² fibre optique - coffrets répartiteur d'étages, équipements",
                "LCS² fibre optique - tiroir optique 19'' haute densité",
                "LCS² fibre optique - tiroir optique 19''",
                "LCS² fibre optique - pigtails, connecteurs à coller et épanouisseurs",
                "LCS² fibre optique - valise et connecteurs à raccordement rapide",
                "LCS² fibre optique - câbles",
                "LCS² fibre optique - cordons de brassage",
                "Programme Mosaic™ -contrôleur, logiciel et points d’accès Wi - Fi"),
            "Systèmes audio / vidéo" => array(
                "Audio vidéo - panneaux de brassage, cordons et câbles",
                "Audio vidéo - prêts à poser HD 15 Programme Mosaic",
                "Audio vidéo - commandes Programme Mosaic",
                "Programme Mosaic™ -switches et répartiteur",
                "Audio vidéo - prises Programme Mosaic",
                "Audio vidéo - autres prises Programme Mosaic et sonorisation de puissance"),
            "LCS² baies et coffrets" => array(
                "Coffrets 19'' LCS² et équipements",
                "Coffret 10'' LCS² et équipements - pour applications petit tertiaire",
                "Coffrets 19'' Linkeo fixes",
                "Baies 19'' LCS² - baies et unités de câblage",
                "Baies serveur 19'' LCS² - baies et équipements",
                "Baies et baies serveur 19'' LCS² - socles et socles réhausseur",
                "Baies et baies serveur 19'' LCS² - entrées de câbles, gestion thermique et supports PDU",
                "Baies et baies serveur 19'' LCS² - gestion de câblage, extension de brassage",
                "Equipements 19'' LCS²",
                "Distribution d'énergie - PDU verticaux, PDU 19'' et kit rail DIN",
                "Distribution d'énergie - PDU 230 V~avec mesure d'intensité",
                "Armoires Altis™ 19'' - IP 55 - IK 10",
                "Baies 19'' Linkeo - baies et équipements",
                "Bâti - rack 19'' et accessoires",
                "Rack mural pour coffrets étanches"),
            "LCS² Data Center" => array(
                "Baies serveur 19'' Data Center LCS² - baies et équipements",
                "Baies serveur 19'' Data Center LCS² - couloir froid confiné et climatisation",
                "Racks 19'' Haute Densité(HD)",
                "Legrand cabling system LCS² - brassage intelligent fibre et cuivre",
                "Legrand cabling system LCS², fibre optique - tiroir fibre optique Haute Densité 19''",
                "Legrand cabling system LCS² - solution préconnectorisée cuivre")),
        "Systèmes de sécurité incendie, alarmes techniques" => array(
            "Eclairage de sécurité" => array(
                "Etiquettes de signalisation - pour blocs d'évacuation",
                "BAES d'évacuation ECO 1 et ECO 2 - pour grands espaces",
                "BAEH ECO 2 SATI Adressable - pour bâtiments d'habitation",
                "BAEH ECO 1 SATI AutoDiag™ -pour bâtiments d'habitation",
                "Télécommandes et accessoires - pour blocs autonomes ou sources centralisées d'éclairage de sécurité et alarmes incendie",
                "Pièces détachées pour blocs autonomes d'éclairage de sécurité - maintenance",
                "Lampes portables d'intervention",
                "Luminaires sur sources centralisées(LSC) - pour éclairage de sécurité",
                "ARCOR™ -blocs autonomes d'éclairage de sécurité",
                "ARCOR™ -plaques de signalisation"),
            "Détection et alarme incendie types 1, 2a, 2b, 3 et 4 - Coupure d’urgence" => array(
                "SSI de catégorie B - équipement d'alarme de type 2a - CMSI conventionnel type B",
                "SSI de catégorie C - équipement d'alarme de type 2b et dispositif de commande et de signalisation(DCS)",
                "SSI de catégorie C, D ou E - équipement d'alarme de type 3",
                "SSI de catégorie D ou E - équipement d'alarme de type 4",
                "BAAS satellites - équipement d'alarme de type 1, 2a et 2b",
                "Diffuseurs lumineux et diffuseurs sonores non autonomes pour alarme incendie - équipement d'alarme de type 1, 2a, 4",
                "Coffrets de sécurité série 90 - Déclencheurs Manuels pour systèmes de sécurité incendie et issues de secours",
                "Détecteur Autonome Déclencheur(SDAD) - DAD, BCM et détecteurs automatiques",
                "Accessoires de mise en sécurité - EAE / EAES / AES et coffret de gestion des asservissements",
                "Accessoires de mise en sécurité - déclencheurs électromagnétiques pour portes coupe - feu et issues de secours",
                "Accessoires de mise en sécurité - commandes de désenfumage",
                "Coffrets de sécurité série 90 - coupure et extinction",
                "Coffrets de sécurité - bris de glace",
                "Coffrets de sécurité - réserve de clés et accessoires"),
            "Alarme intrusion" => array(
                "Alarme intrusion filaire - centrales, clavier, accessoires",
                "Alarme intrusion filaire - détecteurs, avertisseurs"),
            "Alarmes techniques et signalisation" => array(
                "Alarmes techniques modulaires - centrales et détecteurs",
                "Signalisation sonore tertiaire",
                "Signalisation lumineuse",
                "Signalisation lumineuse - accessoires"
            )))));