<p class="mbxxl">40px</p>
<p class="mbxxl">

    <i class="icon-android big-icon"></i>
    <i class="icon-directions big-icon"></i>
    <i class="icon-download big-icon"></i>
    <i class="icon-realize big-icon"></i>
    <i class="icon-inspire big-icon"></i>
    <i class="icon-prepare big-icon"></i>
    <i class="icon-documentation big-icon"></i>
    <i class="icon-catalog big-icon"></i>
    <i class="icon-agency big-icon"></i>
    <i class="icon-career big-icon"></i>
    <i class="icon-certified big-icon"></i>
    <i class="icon-calculate big-icon"></i>
    <i class="icon-score big-icon"></i>
    <i class="icon-localisation big-icon"></i>
    <i class="icon-style big-icon"></i>
    <i class="icon-configuration big-icon"></i>
    <i class="icon-validation big-icon"></i>
    <i class="icon-regulation big-icon"></i>
    <i class="icon-help big-icon"></i>
    <i class="icon-promotion big-icon"></i>
    <i class="icon-standards big-icon"></i>
    <i class="icon-formation big-icon"></i>
    <i class="icon-calendar big-icon"></i>
    <i class="icon-wiring big-icon"></i>
    <i class="icon-application big-icon"></i>
    <i class="icon-showroom big-icon"></i>
    <i class="icon-others big-icon"></i>
    <i class="icon-registrer big-icon"></i>
    <i class="icon-garanty big-icon"></i>
    <i class="icon-immovable big-icon"></i>
    <i class="icon-insatisfaction big-icon"></i>
    <i class="icon-product big-icon"></i>
    <i class="icon-respcom big-icon"></i>
    <i class="icon-ring big-icon"></i>
</p>
<p class="mbxxl">30px</p>
<p class="mbxxl">

    <i class="icon-android medium-icon"></i>
    <i class="icon-play medium-icon"></i>
    <i class="icon-search medium-icon"></i>
    <i class="icon-add-list medium-icon"></i>
    <i class="icon-zoom medium-icon"></i>
    <i class="icon-file medium-icon"></i>

</p>
<p class="mbxxl">20px</p>
<p class="mbxxl">
    <i class="icon-android thin-icon"></i>
    <i class="icon-directions thin-icon"></i>
    <i class="icon-target thin-icon"></i>
    <i class="icon-burger thin-icon"></i>
    <i class="icon-OuiDoo thin-icon"></i>
    <i class="icon-close thin-icon"></i>
    <i class="icon-check thin-icon"></i>
    <i class="icon-apple thin-icon"></i>
    <i class="icon-windows thin-icon"></i>
    <i class="icon-open-bracket thin-icon"></i>
    <i class="icon-close-bracket thin-icon"></i>
    <i class="icon-top-bracket thin-icon"></i>
    <i class="icon-bottom-bracket thin-icon"></i>
    <i class="icon-pointer-top thin-icon"></i>
    <i class="icon-pointer-bottom thin-icon"></i>
    <i class="icon-pointer-vertical thin-icon"></i>
    <i class="icon-arrow-left thin-icon"></i>
    <i class="icon-arrow-right thin-icon"></i>
    <i class="icon-email thin-icon"></i>
    <i class="icon-sent thin-icon"></i>
    <i class="icon-print thin-icon"></i>
    <i class="icon-download thin-icon"></i>
    <i class="icon-clock thin-icon"></i>
    <i class="icon-close-menu thin-icon"></i>
    <i class="icon-tool-empty thin-icon"></i>
    <i class="icon-tool-full thin-icon"></i>
    <i class="icon-foursquare-empty thin-icon"></i>
    <i class="icon-foursquare-full thin-icon"></i>
    <i class="icon-list-empty thin-icon"></i>
    <i class="icon-list-full thin-icon"></i>
    <i class="icon-score-empty-thin thin-icon"></i>
    <i class="icon-score-full-thin thin-icon"></i>
    <i class="icon-search-empty thin-icon"></i>
    <i class="icon-search-thin thin-icon"></i>
    <i class="icon-localisation-empty-thin thin-icon"></i>
    <i class="icon-localisation-full-thin thin-icon"></i>
    <i class="icon-add-list-empty-thin thin-icon"></i>
    <i class="icon-add-list-full thin-icon"></i>
    <i class="icon-user-empty thin-icon"></i>
    <i class="icon-user thin-icon"></i>
    <i class="icon-square-empty thin-icon"></i>
    <i class="icon-square thin-icon"></i>
    <i class="icon-facebook thin-icon"></i>
    <i class="icon-twitter thin-icon"></i>
    <i class="icon-pinterest thin-icon"></i>
    <i class="icon-youtube thin-icon"></i>

</p>
<p class="mbxxl">70px</p>
<i class="icon-play-big very-big-icon"></i>
